title: Measurement and Analysis of Relevant Room Acoustic Parameters in Speech and Language Therapy Rooms and Evaluation of Their Influence on Objective Voice Quality Metrics
description: Additional Content
markdown: kramdown
kramdown:
    math_engine: katex
